name: famto_admin_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.6
  json_annotation: ^4.6.0
  image_picker: ^0.8.4+4
  # image_picker_for_web: ^2.1.12
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  fluttertoast: ^8.2.2
  file_picker: 
  firebase_storage: ^11.2.1
  universal_html: ^2.2.2
  mapmyindia_gl: ^0.3.2
  google_maps: ^6.3.0
  map_location_picker:
  meta: ^1.3.0
  flutter_google_places_web: ^1.0.2
  input_quantity: ^1.2.1
 
  # google_maps_flutter_web: ^0.3.2+2
  # google_maps_flutter_web: ^0.5.0+1
  google_maps_flutter: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
flutter:
  uses-material-design: true
