// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxw72U2Umw3xfUT9VCPzIU1X3NjByo6tU',
    appId: '1:446418708811:web:d173bee49787aa883fe0ce',
    messagingSenderId: '446418708811',
    projectId: 'famto-project',
    authDomain: 'famto-project.firebaseapp.com',
    storageBucket: 'famto-project.appspot.com',
    measurementId: 'G-L1QLD985SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeDg3FSBgKzHl3tmubNUlzDPr5sB4NIg',
    appId: '1:446418708811:android:1060680c1832c5be3fe0ce',
    messagingSenderId: '446418708811',
    projectId: 'famto-project',
    storageBucket: 'famto-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJjUz4iJMFQ4uDyLOmlaUc62cSM1Qpgsg',
    appId: '1:446418708811:ios:dc3ec52754ee0a623fe0ce',
    messagingSenderId: '446418708811',
    projectId: 'famto-project',
    storageBucket: 'famto-project.appspot.com',
    iosBundleId: 'com.example.famtoAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJjUz4iJMFQ4uDyLOmlaUc62cSM1Qpgsg',
    appId: '1:446418708811:ios:dc3ec52754ee0a623fe0ce',
    messagingSenderId: '446418708811',
    projectId: 'famto-project',
    storageBucket: 'famto-project.appspot.com',
    iosBundleId: 'com.example.famtoAdminApp',
  );
}
